#!/bin/bash

#----------------------------------------------------------
# usage: ./rstr $backuped_dir
#----------------------------------------------------------

WHOAMI=`whoami`
if [ ! "$WHOAMI" = "root" ];then
  echo "error: user must be root"
  exit 1
fi

# global conf load
SCRIPT_DIR=`dirname $0`
 . ${SCRIPT_DIR}/../global.conf

# load param
bkuped_dir=$1

if [ ! "$bkuped_dir" ];then
  echo "error: please input backuped directory name"
  exit 1
fi

if [ ! -d ${bkuped_dir} ];then
  echo "error: it seems there is no backuped directory"
  exit 1
fi

# file check
num_chk=`ls ${bkuped_dir}/*core*xz 2>/dev/null | wc -l`
if [ $num_chk -gt 1 ];then
  echo "error: it seems there are more than 2 core.xz file in the directory"
  exit 1
else
  rm -rf $ROOT/databox
  rm -rf $ROOT/users
  cp ${bkuped_dir}/*core*.xz $ROOT/../
  (cd $ROOT/../ && tar -xf *core*.xz)
  chown -R small-shell:small-shell $ROOT
fi

num_chk=`ls ${bkuped_dir}/*www*xz 2>/dev/null | wc -l`
if [ $num_chk -gt 1 ];then
  echo "error: it seems there are more than 2 www.xz file in the directory"
  exit 1
else
  # load web/base
  . $ROOT/web/base
  cp ${bkuped_dir}/*www*.xz ${www}/../
  (cd ${www}/../ && tar -xf *www*.xz)
fi

num_chk=`ls ${bkuped_dir}/*cgi*xz 2>/dev/null | wc -l`
if [ $num_chk -gt 1 ];then
  echo "error: it seems there are more than 2 cgi.xz file in the directory"
  exit 1
elif [ $num_chk -eq 1 ];then
  cp ${bkuped_dir}/*cgi*.xz ${cgidir}/../
  (cd ${cgidir}/../ && tar -xf *cgi*.xz)
fi

num_chk=`ls ${bkuped_dir}/*ssh*xz 2>/dev/null | wc -l`
if [ $num_chk -gt 1 ];then
  echo "error: it seems there are more than 2 ssh.xz file in the directory"
  exit 1
elif [ $num_chk -eq 1 ];then
  if [ ! -d /home/small-shell ];then
    mkdir /home/small-shell
    chown small-shell:small-shell ${small_shell_home}
  fi
  usermod -s /bin/bash small-shell
  cp ${bkuped_dir}/*ssh*.xz /home/small-shell/
  (cd /home/small-shell && tar -xf *ssh*.xz)
fi

echo "-----------------------------------------------------------------------------------------------------"
echo "backup files are restored, please exec gen just in case and restart Base APP and enable e-cron jobs"
echo "-----------------------------------------------------------------------------------------------------"
echo "sudo $ROOT/adm/gen -app #Base APP"
echo "sudo -u small-shell $ROOT/bin/e-cron ls"
exit 0
