#!/bin/bash

#----------------------------------------------------------
# usage: ./rstr $backuped_dir
#----------------------------------------------------------

# load param
bkuped_dir=$1

WHOAMI=$(whoami)
if [ ! "$WHOAMI" = "root" ];then
  echo "error: user must be root"
  exit 1
fi

# global conf load
SCRIPT_DIR=$(dirname $0)
 . ${SCRIPT_DIR}/../global.conf

if [ ! -f ${ROOT}/web/base ];then
  echo "please genterate Base App before restore"
  exit 1
else
  . ${ROOT}/web/base
fi

if [ ! "$bkuped_dir" ];then
  echo "error: please input backuped directory name"
  exit 1
fi

if [ ! -d ${bkuped_dir} ];then
  echo "error: it seems there is no backuped directory"
  exit 1
fi

# file check
num_chk=$(ls ${bkuped_dir}/*core*.xz 2>/dev/null | wc -l)
if [ ! $num_chk -eq 1 ];then
  echo "error: number of backup file seems wrong. please check $bkuped_dir"
  exit 1
else
  rm -rf ${ROOT}/databox
  rm -rf ${ROOT}/users
  (cd ${bkuped_dir} && tar -xf *core*.xz \
  && \cp -Rf small-shell/databox ${ROOT}/databox && \cp -Rf small-shell/users ${ROOT}/users \
  && cp small-shell/web/*.code ${ROOT}/web/ && \cp -Rf small-shell/util ${ROOT}/users/util )
  chown -R small-shell:small-shell $ROOT
fi

num_chk=$(ls ${bkuped_dir}/*www*xz 2>/dev/null | wc -l)
if [ ! $num_chk -eq 1 ];then
  echo "error: number of backup file seems wrong. please check $bkuped_dir"
  exit 1
else
  cp ${www}/app/index.js ${www}/app/index.js.org
  cp ${www}/app/app.sh ${www}/app/app.sh.org
  cp ${www}/def/.small_shell_conf ${www}/def/.small_shell_conf.org
  (cd ${bkuped_dir} && tar -xf *www*.xz && \cp -Rf www/* ${www}/ )
  cp ${www}/app/index.js.org ${www}/app/index.js
  cp ${www}/app/app.sh.org ${www}/app/app.sh
  cp ${www}/def/.small_shell_conf.org ${www}/def/.small_shell_conf
  chmod 755 ${www}/app/index.js
  chmod 755 ${www}/app/app.sh
  chown -R small-shell:small-shell $www

  if [ -f ${www}/app/cert.pem ];then
    ssl_flg=yes
  fi
fi

num_chk=$(ls ${bkuped_dir}/*cgi*xz 2>/dev/null | wc -l)
if [ $num_chk -eq 1 ];then
  (cd ${bkuped_dir} && tar -xf *cgi*.xz && \cp -Rf cgi-bin/* ${cgi_dir}/ )
  chown -R small-shell:small-shell $cgi_dir
fi

num_chk=$(ls ${bkuped_dir}/*ssh*xz 2>/dev/null | wc -l)
if [ $num_chk -eq 1 ];then
  if [ ! -d /home/small-shell ];then
    mkdir /home/small-shell
  fi
  cp ${bkuped_dir}/*ssh*.xz /home/small-shell/
  (cd /home/small-shell && tar -xf *ssh*.xz)
  chown -R small-shell:small-shell /home/small-shell
  mkrep_flg=yes
fi

systemctl restart small-shell

echo "-----------------------------------------------------------------------------------------------------"
echo "Backup files are restored, pelase enable e-cron jobs by manually"
echo "-----------------------------------------------------------------------------------------------------"
echo "sudo -u small-shell ${ROOT}/bin/e-cron ls"

if [ "$ssl_flg" = "yes" ];then
  echo ""
  echo "!! importtant !!"
  echo "Please regenerate Base App using cert and key that is restored in ${www}/app/"
  echo "sudo ${ROOT}/adm/gen -app"
fi

if [ "$mkrep_flg" = "yes" ];then
  echo ""
  echo "Additionally please execute ${ROOT}/util/scripts/mkrep.sh for building replication again"
fi

exit 0
