#!/bin/bash

# global.conf load
SCRIPT_DIR=`dirname $0`
. ${SCRIPT_DIR}/../../global.conf

# load params from que
mailto="$1"
mailfrom="$2"
subject="$3"
contents="$4"

# send mail
echo "$contents" | $SED "s/%%enter/\n/g" | $SED "s/%%double_quote/\"/g" \
| mail -s "$subject" -r $mailfrom $mailto
