#!/bin/bash

# load small-shell params
. %%www/def/.small_shell_conf

echo "Content-Type: text/html"
echo ""

# check master availability
master_chk=$($CURL %%master_base_url%%app | grep %%app)

if [ "$master_chk" ];then
  echo "<meta http-equiv=\"refresh\" content=\"0; url=%%master_base_url%%app\">"
else
  message="error: it seems master server failed, please contact to webadmin"
  cat %%www/def/key_initialize_err.html.def \
  | $SED "s/%%message/${message}/g"
  exit 1
fi

exit 0
