#!/bin/bash

###############################
# controller for FORM
###############################

echo "Content-Type: text/html"
echo ""

# load env
. %%www/def/.env

# load remote addr
remote_addr=$(echo "$REMOTE_ADDR" | $SED "s/:/-/g")

param=$(date +%s)
param="$param:$RANDOM"
count=1
while [ -f %%www/tmp/${param} ]
do
 sleep 0.01
 count=$(expr $count + 1)
 if [ $count -eq 100 ];then
   echo "error: please contact to adimin"
   exit 1
 fi
done

# parse QUERY_STRING
echo "$QUERY_STRING" | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > %%www/tmp/${param}
cat %%www/tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" > %%www/tmp/${param}.load
chmod 755 %%www/tmp/${param}.load

# load query string
.  %%www/tmp/${param}.load
rm  %%www/tmp/${param}*

# auth for small-shell databox
authkey="%%authkey"
auth_req=$(${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:%%app user_agent:%%app)
user_name=$(echo "$auth_req" | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}')
session=$(echo "$auth_req" | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}')
pin=$(echo "$auth_req" | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}')

if [ ! "$session" -o ! "$pin" ];then
  echo "error: internal key authentication failure"
  exit 1
fi

# parse POST data
if [ "$(echo "$REQUEST_METHOD" | grep -i "POST")" ];then

  if [ "$(echo "$CONTENT_TYPE" | grep "application/json")" ];then
    method=json
  elif [ "$(echo "$CONTENT_TYPE" | grep "multipart/form-data")" ];then
    method=multipart
  elif [ "$(echo "$CONTENT_TYPE" | grep "application/octet-stream")" ];then
    method=data-binary
  else
    method=urlenc
  fi

  mkdir %%www/tmp/${session}
  # dump posted data
  dd bs=${CONTENT_LENGTH} of=%%www/tmp/${session}/input 2>/dev/null
  %%www/bin/parse.sh $session $method

fi

#----------------------------
# routing to bin scripts
#----------------------------

if [ ! "$req" ];then
  req=get
fi

case "$req" in

  "get")
    %%www/bin/%%app_get.sh session:$session pin:$pin id:$id remote_addr:${remote_addr};;

  "set")
    %%www/bin/%%app_set.sh session:$session pin:$pin id:$id remote_addr:${remote_addr};;

  *)
    echo "error: wrong request";;

esac

exit 0
